#!/bin/bash
# The production directory
TARGET="/var/www/skyline.com/html"
# The local git
LOCAL="/home/skyline/skyline/www"
# The track branch
LOCAL="master"
while read oldrev newrev ref
do
	if [[ $ref = refs/heads/$BRANCH ]];
	then
		echo "Master ref received.  Deploying ${BRANCH} branch to production..."
		echo "Restarting Aapche"
		sudo service apache2 reload
	else
		echo "Ref $ref successfully received."
		echo " Doing nothing: only the ${BRANCH} branch may be deployed on this server."
	fi
done