#!/bin/bash
# The production directory
TARGET="/var/www/skyline/html"
# The local git
LOCAL="/home/skyline/skyline/www"
# The track branch
LOCAL="master"
while read oldrev newrev ref
do
    if [[ $ref = refs/heads/$BRANCH ]];
    then
        echo "Master ref received.  Deploying ${BRANCH} branch to production..."
        git --work-tree=$TARGET --git-dir=$LOCAL checkout -f
        echo "Restarting Aapche"
        sudo /usr/sbin/apache2ctl restart
    else
        echo "Ref $ref successfully received."
        echo " Doing nothing: only the ${BRANCH} branch may be deployed on this server."
    fi
done