[package]
name = "porcupine-fever"
version = "0.1.0"
authors = ["nihuynh"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
