# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nihuynh <nihuynh@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/03/13 02:35:05 by nihuynh           #+#    #+#              #
#    Updated: 2019/03/13 02:38:52 by nihuynh          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CFLAGS = -Wall -Werror -Wextra

all :
	$(CC) $(CFLAGS) livetime.c tests.c  -g && ./a.out
.PHONY : all
clean :
	rm -f a.out
.PHONY : clean